chore: update deployment

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -8,11 +8,12 @@ on:
 
 jobs:
   publish-npm:
-    name: Publish on NPM
+    name: Publish on NPM and GitHub
     runs-on: ubuntu-latest
     permissions:
       id-token: write
       contents: write
+      packages: write
 
     steps:
       - name: Checkout repository
@@ -34,15 +35,15 @@ jobs:
           if [ ! -f pnpm-lock.yaml ]; then
             echo "::warning::Lockfile tidak ada. Membuat yang baru..."
             pnpm install --lockfile-only
-      
+
             git config --global user.email "hub@erdev.biz.id"
             git config --global user.name "ErBots"
-      
+
             git add pnpm-lock.yaml
             git commit -m "chore: add lockfile [skip ci]"
             git push
           fi
-      
+
           pnpm install --frozen-lockfile
 
       - name: Validate package.json
@@ -55,25 +56,33 @@ jobs:
         id: package_version
         run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
 
-      - name: Setup .npmrc for NPM and GitHub Registry
+      - name: Setup .npmrc
         run: |
           echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
           echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
 
-      - name: Publish to NPM and GitHub Registry
+      - name: Ensure clean git workspace
         run: |
-          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > .npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "::error::Git workspace not clean:"
+            git status --short
+            exit 1
+          fi
 
+      - name: Publish to NPM
+        run: |
           pnpm publish --access public --no-git-checks --registry=https://registry.npmjs.org
-          
+
           CURRENT_VERSION=$(jq -r .version package.json)
           PACKAGE_NAME=$(jq -r .name package.json)
-          
-          npm deprecate "${PACKAGE_NAME}@<${CURRENT_VERSION}" "This version is deprecated. Please upgrade to ${CURRENT_VERSION}."
 
-          pnpm publish --registry=https://npm.pkg.github.com
+          npm deprecate "${PACKAGE_NAME}@<${CURRENT_VERSION}" "This version is deprecated. Please upgrade to ${CURRENT_VERSION}."
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_CONFIG_PROVENANCE: true
+
+      - name: Publish to GitHub Registry
+        run: |
+          pnpm publish --no-git-checks --registry=https://npm.pkg.github.com
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
